### PR TITLE
Update to SQLite 3.11.0 and custom functions

### PR DESCRIPTION
**Pull request by dinedal**
Credit for custom functions to @MFAshby 

I had to do some spacing adjustments to get coffee-script to parse correctly

Also, it looks like the `--join` flag to coffee-script is deprecated.

### CODE REVIEW

**Comment by lovasoa** [comment]
Great, thank you for the work! Can you have a look at the two failing tests?

**Comment by lovasoa** [comment]
Looks like the problem is just that workerjs can't pass typed arrays through workers. I'm going to fix that myself. I'm merging. Thank you!

**Comment by lovasoa** [comment]
I think we should remove the `dbg_func` and `numParams` options from `Database.create_function`. (use `func.length` instead of numParams). And adding and `@example` to the doc comment would be great too. What do you think about it?

**Comment by dinedal** [comment]
> Looks like the problem is just that workerjs can't pass typed arrays through workers. I'm going to fix that myself. I'm merging. Thank you!

Awesome, thanks for that!

> I think we should remove the dbg_func and numParams options from Database.create_function. (use func.length instead of numParams). And adding and @example to the doc comment would be great too. What do you think about it?

I agree 100%.

**Pull request merged**
