### PR TITLE
Make a version of sql.js compiled with ALLOW_MEMORY_GROWTH=1

### LINKED ISSUE #113: Cannot enlarge memory arrays
Hi there

I'm getting tonnes of:

Cannot enlarge memory arrays. Either (1) compile with -s TOTAL_MEMORY=X with X higher than the current value 16777216, (2) compile with ALLOW_MEMORY_GROWTH which adjusts the size at runtime but prevents some optimizations, or (3) set Module.TOTAL_MEMORY before the program runs.

Is there a way to increase the allowed memory? The memory keeps blowing out for me.   
Running in browser, client side

### PR DESCRIPTION
**Pull request by dinedal**
Make a version of sql.js compiled with ALLOW_MEMORY_GROWTH=1 available for everyone, keep it up to date as part of releases

Closes #113

### CODE REVIEW

**Comment by dinedal** [comment]
@lovasoa this is ready for merge as well, would appreciate your thoughts here

**Comment by lovasoa** [comment]
Looks ok! Maybe you should mention the existence of this file in the `README`, so that people knew about it. 

At the end of the README, there is a [downloads section](https://github.com/kripken/sql.js/blob/master/README.md#downloads). You could update it and mention your new memory growth version. And while you're at it, you could also mention `sql-debug.js` there.

**Comment by dinedal** [comment]
@lovasoa any update here?

**Comment by lovasoa** [comment]
Oh, sorry, I didn't see your last commit !

**Comment by lovasoa** [comment]
I just merged. Again, sorry for the delay, I thought you hadn't updated the README.

**Comment by dinedal** [comment]
No worries! Thanks for the merge!

**Comment by danacalcaianu** [comment]
I had the same problem with the memory errors and switched to this version but I'm wondering what are the main differences between the two and what important issues this might rise?

**Pull request merged**
