### PR TITLE
SQLite 3.26.0 update

### LINKED ISSUE #258: SQLite 3.26.0
SQLite 3.26.0 resolves the well-known vulnerability described in <https://blade.tencent.com/magellan/index_en.html>.

I am using SQL.js in a test library for a client, who is using SQLite in a Cordova mobile app. We would like to use the same version of SQLite in both the test library and the mobile app.

### PR DESCRIPTION
**Pull request by brodybits**
* Use `-s WASM=0` to disable wasm in `Makefile`
* Update `c/sqlite3.c` with SQLite `3.26.0`
* Regenerate js/*.js with SQLite 3.26.0

This update is needed for a major client. I hope to see it applied asap.

resolves #258

### CODE REVIEW

**Comment by lovasoa** [comment]
Thank you for the pull request ! However, I would like to have #255 merged first.

**Comment by brodybits** [comment]
Any timeframe when we can finish #255 and apply this update then?

This can be a blocker for people who develop with both SQL.js and SQLite 3.26.0.

**Comment by brodybits** [comment]
I would favor including SQLite 3.26.0 first, which is a security update, since @255 seems to be a breaking change.

**Comment by lovasoa** [comment]
What are the security implications of not having 3.26 for SQL.js ? I read the security announcement you gave a link to, and it does not seem clear it affects sql.js...

**Comment by Taytay** [comment]
I've upgraded to the latest Sqlite 3.28 in #255.

**Comment by Taytay** [comment]
Is this PR valid after #255 @brodybits or does that solve your issue?

**Comment by brodybits** [comment]
As #255 already includes SQLite 3.28, I will close this PR. Thanks @Taytay for your efforts and results!

**Pull request closed without merging**
