### PR TITLE
fixing npm test for nodejs v0.12 (test_worker.js)

### PR DESCRIPTION
**Pull request by kaizhu256**
workerjs depends on JSON.stringify to serialize messages in nodejs
see https://github.com/eugeneware/workerjs/blob/d9812a5409a266d2ab6f0e9db8f1a670acf14b3c/index.js#L19
the v8 engine, since nodejs v0.12, ignores the length property when JSON.stringifying Uint8Array
so we now have to improvise the length property in the test
note that chrome browser doesn't have this limitation, as it seems to pass Uint8Array in the message as a reference
see https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#Passing_data_by_transferring_ownership_(transferable_objects)

### CODE REVIEW

**Comment by lovasoa** [comment]
If I understand well, the problem is that workerjs can't pass UInt8Arrays in messages.
So, we have a bug in the code, that is supposed to work on node too.
So we should definitely fix the code rather than the tests.
Maybe we need to open an issue in workerjs.

**Comment by kaizhu256** [comment]
looking @ the source code @ https://github.com/eugeneware/workerjs/blob/d9812a5409a266d2ab6f0e9db8f1a670acf14b3c/index.js#L19, 
i get the feeling workerjs's maintainer (if i were in his chair) would feel it incredibly hacky & unmaintainable to make a special serialization and de-serialization code just for Uint8Arrays.  in the overall scheme, its priority would prolly be assigned lower than other special-cases like datetime and regex objects, and where would these special cases end?

since workerjs code is pretty simple, with zero dependencies, i think a better solution is prolly just implement a custom nodejs polyfill for sql.js with Uint8Array support (and maybe datetime as well).

**Comment by lovasoa** [comment]
They would end where [the specification](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm) ends.

What do you mean by "implement a polyfill" ? workerjs is already a polyfill. Maybe what we need is implement the structured clone algorithm in Javascript as a separate project, and add this project as a dependency to workerjs.

**Comment by kaizhu256** [comment]
i mean we inline our own Uint8Array hacked version of workerjs in https://github.com/kripken/sql.js/blob/master/coffee/worker.coffee.  i like the fact sql.js has zero dependencies, and i like to keep it that way :)

**Comment by lovasoa** [comment]
It's false, sql.js already depends on workerjs when used in node.

**Comment by kaizhu256** [comment]
only as a devDependency for testing

**Comment by lovasoa** [comment]
No, you actually need it if you want to use sql.js in node.

**Comment by lovasoa** [comment]
It's not in the dependencies so that it's not downloaded automatically.

**Comment by lovasoa** [comment]
But  sql.js in node is something that is not massively used, and sql.js in node using a worker is something that must be even less used, I don't think this issue is very important...

**Comment by kaizhu256** [comment]
it could get massively used, if its hyped as a full-text-search engine (via fts4) for both the browser and nodejs, with no dependency crap.  there are so many web problems, where u want an fts engine that just works and is easy to deploy.

**Comment by lovasoa** [comment]
Yes, but the performance and complexity penalty of compiling it through emscripten, makes it almost irrelevant compared to a natively compiled SQLite.

**Pull request closed without merging**
