### PR TITLE
Compile sql.js to wasm instead of "just" asm.js

### LINKED ISSUE #115: Test failures on compiling with latest Emscripten
issue55 is failing when compiling with latest Emscripten at

``` sql
db.run("INSERT INTO networklocation (x, y, network_id, floor_id) VALUES (?, ?, ?, ?)", [123, 123, 1, 1]);
```

Error: NOT NULL constraint failed: networklocation.x

But if I run with the prepared statement:

``` sql
  var stmt = db.prepare("INSERT INTO networklocation (x, y, network_id, floor_id) VALUES (?, ?, ?, ?)");
  stmt.bind([123, 123, 1, 1]);
  stmt.step();
  stmt.free();
```

Everything works fine.

```
coffee -v
CoffeeScript version 1.9.3

emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.34.3
clang version 3.7.0
Target: x86_64-apple-darwin14.4.0
Thread model: posix
INFO     root: (Emscripten: Running sanity checks)
```

### LINKED ISSUE #173: sql.js's process.on('uncaughtException') causing problems
This library binds to uncaughtException as follows:

``` javascript
process['on']('uncaughtException', function(ex) {
    // suppress ExitStatus exceptions from showing an error
    if (!(ex instanceof ExitStatus)) {
      throw ex;
    }
  });
```

This causes incompatibilities with global uncaughtException handlers as seen in [this issue - related to electron](https://github.com/electron/electron/issues/7876).
Can sql.js's uncaughtException handler be changed? What are the implications of removing it?

### LINKED ISSUE #210: make sqlite v3.20.0
make
# Generate llvm bitcode
/home/kirill/emsdk/emscripten/1.37.13/emcc -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_DISABLE_LFS -DLONGDOUBLE_TYPE=double -DSQLITE_INT64_TYPE="long long int" -DSQLITE_THREADSAFE=0 -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_FTS3_PARENTHESIS c/sqlite3.c -o c/sqlite3.bc
c/sqlite3.c:385:5: error: token is not a valid binary operator in a preprocessor subexpression
#if SQLITE_INT64_TYPE
    ^~~~~~~~~~~~~~~~~
<command line>:8:32: note: expanded from here
#define SQLITE_INT64_TYPE long long int
                          ~~~~ ^
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
Makefile:42: ошибка выполнения рецепта для цели «c/sqlite3.bc»
make: *** [c/sqlite3.bc] Ошибка 1

### LINKED ISSUE #219: Is there a WebAssembly version of sql.js?
I have a limited understanding of WebAssembly, but my understanding is that we'd see better performance if this was actually compiled directly to WebAssembly, rather than "only" asm.js. If that's correct, has anyone made the edits to the toolchain to support it, or are there pre-compiled files available on any of this projects' branches? If I wanted to look into doing so, can anyone point me in the right direction to begin digging in?

### LINKED ISSUE #232: writeStringToMemory is deprecated and should not be called! Use stringToUTF8() instead!
I'm getting this warning when using the latest master version of sql.js:

    writeStringToMemory is deprecated and should not be called! Use stringToUTF8() instead!

Any idea on how to resolve?

### LINKED ISSUE #251: writeStringToMemory is deprecated and should not be called! Use stringToUTF8() instead!
Maybe it should be considered to update it.

### LINKED ISSUE #258: SQLite 3.26.0
SQLite 3.26.0 resolves the well-known vulnerability described in <https://blade.tencent.com/magellan/index_en.html>.

I am using SQL.js in a test library for a client, who is using SQLite in a Cordova mobile app. We would like to use the same version of SQLite in both the test library and the mobile app.

### LINKED ISSUE #262: Build without greedy uncaughtException handler
This is related to #173.

I wrote up what is happening here: https://github.com/danielbarela/sqljs-uncaughtexception

This issue in emscripten indicates that the library can be built without the greedy exception handler:
https://github.com/emscripten-core/emscripten/issues/5957

Can this option be added to the sql.js build and republished?

### PR DESCRIPTION
**Pull request by Taytay**
Emits WebAssembly and asm.js targets.
Upgrades to Version 3.28.0 of Sqlite
Upgrades to Version 1.38.30 of Emscripten

I wanted to use the built-in modularize code, but I ran into some of the issues spelled out in https://github.com/kripken/emscripten/issues/5820, so I have continued the sql.js tradition of modularizing it manually via pre and post files. There is now a promise exported that you wait on, and this promise resolves with the `SQL` module. This way, SQL isn't usable until the WebAssembly or asm.js has been loaded.

Since I made some more fundamental changes to how the module is loaded, and since this project now emits so many targets, I am not sure if it would be better to fork sql.js? 
sql.js is no longer drop-in compatible with previous versions due to the async loading. I have documented this here in README.md: https://github.com/kripken/sql.js/pull/255/files#diff-04c6e90faac2675aa89e2176d2eec7d8

I also ran into a bug involving the creation of the sql-optimized file, so I restructured the Makefile a fair amount. It's not as DRY/fancy now, but it was easier to fix the issue. I have also made it easier to update the version of Sqlite used when compiling by borrowing heavily from https://github.com/mandel59/sqlite-wasm

It's worth mentioning that the worker test running in the node environment does not work when loaded with a WebWorker simulator, so I have skipped that test for now. 

This PR cleans up other issues as well:
Fixes #219 
Fixes #173 
Fixes #262  
Fixes #258 
Fixes #251  
Fixes #232 
Fixes #210 
Fixes #115 

I look forward to hearing your thoughts.

TODOs:

- [x] Ensure that the mechanism for loading the module asynchronously works well in the browser
- [x] Update the readme for browser and Node usage
- [x] Add myself to AUTHORS
- [x] Bump major version

### CODE REVIEW

**Comment by mikeptweet** [comment]
Would it be possible to use/test with the latest sqlite version?

**Comment by Taytay** [comment]
@mikeptweet, I certainly could. I am already a bit nervous about the sheer number of things I'm recommending change, but I could create another branch with this. If I make the Makefile improvements I'd like to (essentially copying @mandel59's work here https://github.com/mandel59/sqlite-wasm), this will get even easier.

**Comment by lovasoa** [comment]
It seems like a lot of good work to me ! If @kripken and @dinedal do not see anything to say, I will merge this.

**Comment by Taytay** [comment]
Thanks for looking @lovasoa! 

It is worth calling out that this changes the nature of the loading from synchronous to async, even in the non-WASM case, so if you are following semantic versioning, it would be worth bumping to a new major version number. I would hate to break someone's app that is depending on this. 

I'm happy to make the bump myself, but it felt presumptuous. Let me know how you'd like me to proceed.

**Comment by dinedal** [comment]
Yes, I have something to say... THANKS! Nice work, well done 👏

**Comment by dinedal** [comment]
I'm in favor of bumping the major version number here too.

**Comment by lovasoa** [comment]
@Taytay yes, do the version bump ! It is not presumptuous at all. You have done a lot of work on this. You should also add yourself to the [AUTHORS](https://github.com/kripken/sql.js/blob/master/AUTHORS) of this project.

**Comment by lovasoa** [comment]
So, any news @Taytay ?

**Comment by Taytay** [comment]
Sorry for the stall on this folks! I got covered up with other work after my sprint here. I'll try to bring this home soon.

**Comment by lovasoa** [comment]
No worries :) Thank you again for your work.

**Comment by lovasoa** [comment]
@Taytay : when do you think you can finish that ?

**Comment by brodybits** [comment]
I hope this will include SQLite 3.26.0 security update (#258).

**Comment by Taytay** [comment]
Update: 
I am sorry for the delay here folks. I got a chance to work on this again today, and in an effort to make things clean and consistent, I've made changes to the folder structure and modularization method. In particular, I am not satisified with the current state of emcc's `MODULARIZE=1`. It has some bugs, especially around its use of `then` (https://github.com/kripken/emscripten/issues/5820) , and furthermore, it follows a pattern that allows the `Module` and its methods to be used well before the underlying WASM has finished loading. Some people have suggested adding a `ready` promise property to the exported `Module` object that can be waited upon before using the library, but I believe it's too easy to forget to do that, especially for existing consumers of this library that are used to using things synchronously. So, I've modified the pre and post shell scripts to do my own modularization. 

I've updated the README to show how to use this new async loading mechanism:
```js
var initSqlJs = require('sql-wasm.js');

// or initSqlJs = window.initSqlJs if you are in a browser

initSqlJs().then(function(SQL){

  // Create a database
  var db = new SQL.Database();
  ...
});
```

I've also renamed a number of folders/files to make them more straightforward. In particular:
I have made an effort to distinguish between source/input files and output files. 
`js/` has been renamed to `dist/`
Now every file in the `dist/` folder specifies whether it is asm.js-based or wasm-based. Previously the files that did not specify (like `sql.js`) were in fact asm.js based. Since that is only offered for compatibility reasons, it didn't seem fitting to have an asm.js file be the default for this lib. 

@brodybits : I am happy to include 3.26 of Sqlite.

At this point, my main TODOs before merging are around ensuring that this library is usable not just in Node (CommonJS), but in the browser as well. I've updated the README, but it still needs notes about the breaking changes between this 1.0+ version and previous versions.

**Comment by Taytay** [comment]
One more thing: I believe that we should consider removing the compiled assets from this repo, and instead make them a part of a Github Release process. You'd be able to download the compiled assets from Github's release page instead of cloning the repo. The `dist` folder currently takes up 43MB for a single version. Given that it is likely to change frequently, and given that some of it is essentially, it is likely not to diff well. This will bloat the repo considerably. Making this move is an even larger change, so I am hesitant to do it here, but I wanted to mention it.

**Comment by brodybits** [comment]
Considering that this already seems to be a breaking change, I would favor disabling some SQLite features to reduce the build size as @Taytay tried in <https://github.com/Taytay/sql.js/pull/1>.

Thanks again @Taytay!

**Comment by lovasoa** [comment]
@brodybits : Disabling features would have to be discussed separately. I don't think this is something we want to do here.

@Taytay : Yes, we can remove dist/ from git.

**Comment by Taytay** [comment]
@lovasoa : As I mentioned, my remaining tasks are improving the README and testing the browser (possibly even adding some browser tests). Do you see anything else in the code that you would like me to change? With this being a 1.0 release, and a pretty substantial change, I want to make sure that you like the approaches I'm taking.

**Comment by mikeptweet** [comment]
Any chance this will ever get merged with the master branch?

**Comment by danielbarela** [comment]
Is there any status update to this pull request?  Since this seems to be the long pole pull request blocking #260 I was hoping we could update the build flags to include -s NODEJS_CATCH_EXIT=0 which will fix the issue brought up in #173 and #262

**Comment by Taytay** [comment]
Hey @danielbarela - I haven't had any "evening-time" to work on this PR since I last committed. It's quite close, but not at 100%. At this point, I think we should leave out any other changes and just try to get it finished. It needs some simple things like documentation in the README to show how it works, and I might change the name of the main class back to `SQL` to maintain compatibility. I'm not sure if anyone wants to pick up the torch to finish cleaning this up or tell me what else needs to be cleaned up, but I certainly wouldn't take offense.

These are my last real TODOs from a previous comment:
> At this point, my main TODOs before merging are around ensuring that this library is usable not just in Node (CommonJS), but in the browser as well. I've updated the README, but it still needs notes about the breaking changes between this 1.0+ version and previous versions.

**Comment by Taytay** [comment]
Okay - I had another go at it, fixed bugs with the worker, added examples in code and the reader, and might get more time tomorrow. @lovasoa, let me know if you have any thoughts.

**Comment by lovasoa** [comment]
Thank you for your work @Taytay. I'll have a look at it as soon as I can.

**Comment by nullrocket** [comment]
Excited to see this, I have been using this branch in our beta for a while with a few tiny JS api patches. Thanks for the hard work, I look forward to contributing more actively.

**Comment by Taytay** [comment]
@nullrocket : Thanks! I was excited to try and wrap this up. Any chance you could point me to your patches or even lightly explain them so I could see if they would be helpful to incorporate in another PR?

**Comment by Taytay** [comment]
@lovasoa : I believe that this is ready for a final review. I edited the original text of the PR to describe it more accurately. I also added more commits today to upgrade to the latest SQLite and Emscripten, as well as fix some other issues.

**Comment by nullrocket** [comment]
@Taytay My patches were just a bit of wrapping around the api in the same spirit as these https://github.com/kripken/sql.js/issues/91 probably nothing useful at this point or very well thought out.  

Once this lands  I will probably work towards wrapping the API to match at least the features I need from https://github.com/journeyapps/node-sqlcipher  This is not super useful to most and  way beyond the scope of sql.js, but the work of implementing some of the codecs and extensions out there like https://www.sqlite.org/loadext.html will probably be useful.

**Pull request merged**
