### PR TITLE
Adds extension-functions.c from http://www.sqlite.org/contrib

### PR DESCRIPTION
**Pull request by dinedal**
Description:
> Provide mathematical and string extension functions for SQL queries using the loadable extensions mechanism. Math: acos, asin, atan, atn2, atan2, acosh, asinh, atanh, difference, degrees, radians, cos, sin, tan, cot, cosh, sinh, tanh, coth, exp, log, log10, power, sign, sqrt, square, ceil, floor, pi. String: replicate, charindex, leftstr, rightstr, ltrim, rtrim, trim, replace, reverse, proper, padl, padr, padc, strfilter. Aggregate: stdev, variance, mode, median, lower_quartile, upper_quartile.

### CODE REVIEW

**Comment by lovasoa** [comment]
Do you think it's a good idea to include extension functions by default? It makes `sql.js` bigger, and
since the beginning of the project, there have been requests for spatialite support (#89) and encryption (#54), but never for these functions.

Maybe it would be a better solution to be able to compile them if needed, with something like `make sql-extension-functions.js`.

**Comment by dinedal** [comment]
I understand, I went with this approach since I felt these functions fleshed out SQLite as a fuller database, most people expect a `stdev()` and the other aggregate functions.

But yes, can make this a separate file.

**Comment by dinedal** [comment]
I'm not particularly fond of the things I had to do to the Makefile to do this.

Ideas? Thoughts? I feel like we need a cleaner way to do these kinds of builds and testing if more "variants" of SQLite are done.

**Comment by dinedal** [comment]
It's probably worth noting the size difference here is really small after optimizations (in bytes)

```
4192	./js/sql-extension-functions.js
4096	./js/sql.js
```

**Comment by lovasoa** [comment]
Oh, I didn't realise how small the size difference was. And you are right, the Makefile gets really ugly... So, if you think it should be included be default, I think we'll do this. 

@kripken: what do you think about that?

**Comment by kripken** [comment]
Sounds ok to me too, to include by default.

**Comment by dinedal** [comment]
Thanks, I can make the change to include this by default.

**Comment by lovasoa** [comment]
Let's do it then :)

**Comment by lovasoa** [comment]
If you have time, and are still interested in doing awesome things for this project, you can have a look at #128

**Comment by dinedal** [comment]
I don't mind, I'll take a look

**Comment by tomthe** [comment]
I am confused: are the extension-functions somehow availible in sql.js? Because when I test them, I get an error like: "no such function: acos"

**Pull request merged**
